create table if not exists modeling_price_features (
    timestamp_utc timestamptz primary key,
    price_eur_mwh numeric not null,
    consumption_mwh numeric not null,
    total_production_mwh numeric not null,
    nuclear_mwh numeric,
    thermal_mwh numeric,
    gas_mwh numeric,
    coal_mwh numeric,
    oil_mwh numeric,
    wind_mwh numeric,
    solar_mwh numeric,
    hydro_mwh numeric,
    bioenergy_mwh numeric,
    physical_exchanges_mwh numeric,
    renewable_mwh numeric,
    fossil_mwh numeric,
    renewable_share numeric,
    nuclear_share numeric,
    fossil_share numeric,
    residual_demand_mwh numeric,
    supply_demand_gap_mwh numeric,
    avg_temperature_c numeric,
    min_temperature_c numeric,
    max_temperature_c numeric,
    avg_apparent_temperature_c numeric,
    avg_wind_speed_mps numeric,
    avg_wind_speed_80m_mps numeric,
    avg_shortwave_radiation_wm2 numeric,
    avg_cloud_cover_pct numeric,
    avg_precipitation_mm numeric,
    total_precipitation_mm numeric,
    avg_surface_pressure_hpa numeric,
    hour integer not null,
    day_of_week integer not null,
    month integer not null,
    day_of_year integer not null,
    is_weekend boolean not null,
    is_peak_hour boolean not null,
    hour_sin numeric not null,
    hour_cos numeric not null,
    day_of_year_sin numeric not null,
    day_of_year_cos numeric not null,
    price_lag_1h numeric,
    price_lag_24h numeric,
    price_lag_168h numeric,
    price_rolling_mean_24h numeric,
    price_rolling_mean_168h numeric,
    consumption_lag_24h numeric,
    wind_lag_24h numeric,
    solar_lag_24h numeric,
    created_at timestamptz not null default now()
);

create index if not exists idx_modeling_price_features_timestamp
    on modeling_price_features (timestamp_utc);

